---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: server
    image: plugins/docker:linux-amd64
    settings:
      dockerfile: build/package/Dockerfile
      target: release-server
      repo: zhydzetski/faraway-tt-server
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
  - name: client
    image: plugins/docker:linux-amd64
    settings:
      dockerfile: build/package/Dockerfile
      target: release-client
      repo: zhydzetski/faraway-tt-client
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
trigger:
  branch:
    - master