version: "3.4"

services:
  server:
    build:
      context: .
      dockerfile: build/package/Dockerfile
      target: release-server
    environment:
      LISTEN_ADDR: ":7777"
      POW_DIFFICULTY: 100
    restart: on-failure
  client:
    build:
      context: .
      dockerfile: build/package/Dockerfile
      target: release-client
    command: ["--server-addr=server:7777"]
    restart: always