version: '3'

tasks:
  lint:
    cmds:
      - golangci-lint.exe run --fix
  test:
    cmds:
      - go test ./... -coverprofile cover.out
  coverage:
    deps: [test]
    cmds:
      - go tool cover -func cover.out