version: '3'

tasks:
  lint:
    cmds:
      - golangci-lint.exe run --fix
  test:
    cmds:
      - go test -coverpkg=./... -coverprofile cover.out -covermode=atomic ./...
  coverage:
    deps: [test]
    cmds:
      - go tool cover -func cover.out
  docker-build-server:
    cmds:
      - docker build -f build/package/Dockerfile --rm --target release-server -t faraway-tt/server .
  docker-build-client:
    cmds:
      - docker build -f build/package/Dockerfile --rm --target release-client -t faraway-tt/client .
  demo:
    cmds:
      - docker-compose up --build --scale server=2 --scale client=2